[package]
name = "rust_of_life"
version = "0.1.0"
edition = "2021"
authors = ["Marcos Pardo Estelles <marcos@estelles.es>"]
license = "GPL-3.0"
keywords = ["gamedev"]


[dependencies]
rand = "0.8.5"
raylib = "3.7.0"
